version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: currency_db_container
    environment:
      POSTGRES_USER: xchart
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: currency_db
    ports:
      - "5432:5432"
    volumes:
      - postgresql_data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    container_name: currency_cache_container
    ports:
      - "6379:6379"
volumes:
  postgresql_data: